version: '3'

services:

  database:
    container_name: database
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=tomidea
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=babatomide
    hostname: mysqlserverhost
    ports:
      - 3306:3306
  
  todo_app:
    container_name: todo_app
    build: .
    image: tomidea/todo_app:latest
    restart: always
    depends_on:
      - database
    environment:
      - DB_HOST=mysqlserverhost
      - DB_DATABASE=homestead
      - DB_USERNAME=homestead
      - DB_PASSWORD=tomidea
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=7GTl5BaI32DLmrH7lBuUkIDW5LMBB14y
    ports:
      - 80:80
    